version: 2

# NOTE: If you modify this file to install a package with pip or apt, please
#       verify if we need the same package added to our CI.
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
    nodejs: "16"
  apt_packages:
    - graphviz
    - tree

sphinx:
  configuration: src/conf.py
  builder: html

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - all
