services:
  - docker

language: python
python:
  - 3.8

cache:
  pip: true

branches:
  only:
    - main
    - /.*/

install:
  - pip install -U pip setuptools wheel typing
  - pip install -e .[all]

script:
  - make RUNNER=cwltool unittest-examples
