sudo: required
services:
  - docker

language: python
python:
  - 2.7
  - 3.6

branches:
  only:
    - gh-pages
    - /.*/

before_script:
  - pip install cwltool cwltest html5lib

script:
  - make RUNNER=cwltool unittest-examples
